---
title: "Tarantino"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(svglite)
knitr::opts_chunk$set(
  dev = "svglite",
  fig.ext = ".svg"
)
```

## Hypothesis
- Different word per Movie
- Shift in words per Movie (color band on a time series)
- Death Timeline
- Death count



- starting time 15:32


```{r}
tarantino = read.table('./data/data/tarantino/tarantino.csv', header = TRUE,sep = ",")
tail(tarantino)
```


```{r fig.width=3, fig.height=9}
ggplot(subset(tarantino, type=='word'), aes(reorder(word, word, function(x) length(x) ))) + geom_bar() + coord_flip()
```



```{r fig.width=3, fig.height=8}
ggplot(subset(tarantino, type=='word'), aes(word)) + geom_bar() + coord_flip()
```


```{r}
ggplot(subset(tarantino, type=='word'), aes(reorder(movie, movie, function(x) length(x) ))) + geom_bar() + coord_flip()
```



```{r fig.width=5, fig.height=5}
# tarantino %>% 
# tarantino %>% filter(type=='word') %>% group_by(word) %>% summarise(word_count=count(word))

# type(table(tarantino$word)

# tarantino %>% .(word)
# %>% summarise

# diamonds %>% group_by(clarity) %>% summarise(count=)

# diamonds %>% group_by(clarity) %>% summarise(carat_median = median(carat), price_median = median(price))

# tarantino %>% filter(word != '') %>%  group_by(movie, word) %>%  summarise(w_count=n()) 
# %>% group_by(movie)
# %>% group_by(movie) %>% top_n(10, wt=w_count)

# %>% summarise(w_count=n()) %>% arrange(movie, desc( w_count))
# %>% head

# summary(tarantino)




# ggplot(subset(tarantino, type=='word'), aes(reorder(word, word, function(x) length(x) ))) + geom_bar() + coord_flip()+ facet_wrap(~movie)





# data$word_count

# reorder(word, word, function(x) length(x) )

# help(geom_bar)

```

```{r}
data = tarantino %>% filter(word != '') %>% group_by(word) %>% summarise(word_count=n())  %>% arrange(desc(word_count)) %>% head


ggplot(data, aes(reorder(word, word_count, function(x) print(x) ) , word_count)) + geom_col() + coord_flip()
```




```{r}
data = tarantino %>% filter(word != '') %>% group_by(movie, word) %>% summarise(word_count=n()) %>% top_n(5, wt=word_count)

level = tarantino %>% filter(word != '') %>% group_by(word) %>% summarise(word_count=n()) %>% arrange(word_count)

data$word = factor(data$word, levels = level$word)

ggplot(data, aes(word , word_count)) + geom_col() + coord_flip()+ facet_wrap(~movie)

# ggplot(data, aes(reorder(word, word_count, function(x) print(x) ) , word_count)) + geom_col() + coord_flip()




```
